extends SceneTree
func _initialize(): call_deferred('_run')
func _run():
 var engine=root.get_node('LuaScriptEngine')
 var palette=preload('res://addons/roblox_runtime/brick_color_palette.gd')
 assert(palette.COLORS.size()==208)
 assert(palette.resolve(192).is_equal_approx(Color8(105,64,40)))
 assert(palette.resolve('Reddish brown').is_equal_approx(palette.resolve(192)))
 assert(palette.resolve(21)!=palette.resolve(23), 'Distinct team colors must not collapse to white')
 var part=MeshInstance3D.new()
 part.mesh=BoxMesh.new()
 root.add_child(part)
 engine._apply_manifest_part_appearance(part,{'BrickColor':192})
 assert(part.material_override.albedo_color.is_equal_approx(palette.resolve(192)))
 var imported=preload('res://addons/rbxl_importer/material_cache.gd').new().get_part_material({'BrickColor':192})
 assert(imported.albedo_color.is_equal_approx(part.material_override.albedo_color))
 var context=Node.new()
 part.add_child(context)
 var result=engine.start_script("script.Parent.BrickColor = BrickColor.new('Bright blue')",context,{'realm':'server'})
 assert(result.ok)
 await create_timer(0.1).timeout
 assert(part.material_override.albedo_color.is_equal_approx(palette.resolve(23)))
 print('BRICK_COLOR_PALETTE_OK')
 quit()
