import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import express from 'express';
import {mountLegends,LEGENDS_EDITOR} from './roblox_legends.mjs';
const db=new DatabaseSync(':memory:');
const app=express();
mountLegends(app,db,async req=>({record:{id:req.headers.authorization}}),async()=>[{id:'a',name:'NDS',is_published:true,is_public:false,visibility:''},{id:'private',is_published:false}]);
const server=app.listen(0,'127.0.0.1');
await new Promise(r=>server.once('listening',r));
const url=`http://127.0.0.1:${server.address().port}/api/legends`;
const post=(user,body)=>fetch(url,{method:'POST',headers:{authorization:user,'content-type':'application/json'},body:JSON.stringify(body)});
assert.equal((await post('pavelord',{map_id:'a',year:2011})).status,403);
assert.equal((await post(LEGENDS_EDITOR,{map_id:'private',year:2011})).status,404);
assert.equal((await post(LEGENDS_EDITOR,{map_id:'a',year:2011})).status,200);
assert.equal((await (await fetch(url)).json()).games[0].year,2011);
await post(LEGENDS_EDITOR,{map_id:'a',year:2012});
assert.equal((await (await fetch(url)).json()).games.length,1);
await post(LEGENDS_EDITOR,{map_id:'a',remove:true});
assert.equal((await (await fetch(url)).json()).games.length,0);
await new Promise(r=>server.close(r));db.close();
console.log('[legends] PASS permanent-ID authorization, published-only, add/update/remove');
